version: '2'
volumes:
        unifi-data:
        unms-data:
        nginx-data:
services:
        nginx:
                build: ./nginx
                ports:
                        - "443:443"
                        - "80:80"
                volumes:
                        - "nginx-data:/app/data"
                links:
                        - "unifi"
                        - "unms"
        unifi:
                image: jacobalberty/unifi:5.8.24
                ports:
                        # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
                        - "10001:10001/udp" # AP discovery 
                        - "3478:3478/udp" # STUN
                        - "6789:6789" # Mobile speed tests
                        - "8080:8080" # Device controller communication
                volumes:
                        - "unifi-data:/unifi"
        unms:
                image: oznu/unms:0.12.1
                volumes:
                        - "unms-data:/config"
