version: '2'
volumes:
        unifi-data:
        unms-data:
        nginx-data:
        letsencrypt:
services:
        ddclient:
                build: ./ddclient-cloudflare
                privileged: true
        nginx:
                build: ./nginx
                privileged: true
                ports:
                        - "443:443"
                volumes:
                        - "nginx-data:/app/data"
                        - "letsencrypt:/etc/letsencrypt"

                links:
                        - "unifi"
                        - "unms"
        unifi:
                image: jacobalberty/unifi:arm32v7-beta
                ports:
                        # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
                        - "3478:3478/udp" # STUN
                        - "6789:6789" # Mobile speed tests
                        - "8080:8080" # Device controller communication
                        - "10001:10001/udp" # AP discovery
                volumes:
                        - "unifi-data:/unifi"
        unms:
                image: oznu/unms:0.13.1-armhf
                volumes:
                        - "unms-data:/config"
                ports:
                        - "2055:2055/udp" # Netflow
